import { NextResponse } from "next/server";
import { z } from "zod";

import { requireAdminSession } from "@/lib/api-guard";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { itemSchema } from "@/lib/validations/admin/item";
import { itemFormToRow } from "@/lib/item-mapper";
import { syncAutoGeneratedEquipMovements } from "@/lib/movement-mapper";

/** Espelha o `fromid`/`toid` do items.xml: cria vários items com os mesmos atributos, apenas
 * variando o id no intervalo informado. */
const MAX_RANGE = 500;

const rangeSchema = z
  .object({
    fromId: z.number().int().min(1),
    toId: z.number().int().min(1),
    item: itemSchema.omit({ id: true }),
  })
  .refine((data) => data.toId >= data.fromId, {
    message: "O id final deve ser maior ou igual ao id inicial.",
    path: ["toId"],
  })
  .refine((data) => data.toId - data.fromId + 1 <= MAX_RANGE, {
    message: `Range muito grande (máximo ${MAX_RANGE} ids por vez).`,
    path: ["toId"],
  });

export async function POST(request: Request) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const body = await request.json();
  const parsed = rangeSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Dados inválidos." },
      { status: 422 },
    );
  }

  const { fromId, toId, item } = parsed.data;
  const ids = Array.from({ length: toId - fromId + 1 }, (_, i) => fromId + i);

  const existing = await prisma.item.findMany({
    where: { id: { in: ids } },
    select: { id: true },
  });
  if (existing.length > 0) {
    return NextResponse.json(
      {
        error: `Já existem items com os ids: ${existing.map((e) => e.id).join(", ")}.`,
      },
      { status: 409 },
    );
  }

  await prisma.item.createMany({
    data: ids.map((id) => itemFormToRow({ ...item, id })),
  });

  for (const id of ids) {
    await syncAutoGeneratedEquipMovements(prisma, id, item.slotType);
  }

  await logAudit({
    accountId: Number(session.user.id),
    action: "create",
    entity: "item",
    metadata: { name: item.name, fromId, toId, count: ids.length },
  });

  return NextResponse.json({ created: ids.length, fromId, toId }, { status: 201 });
}
