import { NextResponse } from "next/server";
import { z } from "zod";

import { requireAdminSession } from "@/lib/api-guard";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { itemSchema, type ItemInput } from "@/lib/validations/admin/item";
import { itemFormToRow, itemRowToFormInput } from "@/lib/item-mapper";
import { isSameItemConfig } from "@/lib/item-compare";
import { syncAutoGeneratedEquipMovements } from "@/lib/movement-mapper";
import { withAudit } from "@/lib/api-audit-wrapper";

/** Espelha o `fromid`/`toid` do items.xml: cria vários items com os mesmos atributos, apenas
 * variando o id no intervalo informado. */
const MAX_RANGE = 500;

const rangeOverrideSchema = z.object({
  id: z.number().int(),
  clientId: z.number().int().nullable().optional(),
  lookTypeId: z.number().int().nullable().optional(),
});

const rangeSchema = z
  .object({
    fromId: z.number().int().min(1),
    toId: z.number().int().min(1),
    item: itemSchema.omit({ id: true }),
    overrides: z.array(rangeOverrideSchema).optional().default([]),
  })
  .refine((data) => data.toId >= data.fromId, {
    message: "O id final deve ser maior ou igual ao id inicial.",
    path: ["toId"],
  })
  .refine((data) => data.toId - data.fromId + 1 <= MAX_RANGE, {
    message: `Range muito grande (máximo ${MAX_RANGE} ids por vez).`,
    path: ["toId"],
  });

export const POST = withAudit(async function POST(request: Request) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const body = await request.json();
  const parsed = rangeSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Dados inválidos." },
      { status: 422 },
    );
  }

  const { fromId, toId, item, overrides } = parsed.data;
  const ids = Array.from({ length: toId - fromId + 1 }, (_, i) => fromId + i);

  // Permite que cada id do range tenha seu próprio client_id/looktype (aba "Outras sprites" do
  // formulário) mesmo compartilhando todos os demais atributos do item base.
  const overrideById = new Map(overrides.map((o) => [o.id, o]));
  const incomingById = new Map<number, ItemInput>(
    ids.map((id) => {
      const override = overrideById.get(id);
      return [
        id,
        {
          ...item,
          id,
          clientId: override?.clientId !== undefined ? override.clientId : item.clientId,
          lookTypeId: override?.lookTypeId !== undefined ? override.lookTypeId : item.lookTypeId,
        },
      ];
    }),
  );

  const existingRows = await prisma.item.findMany({ where: { id: { in: ids } } });
  const existingById = new Map(existingRows.map((row) => [row.id, itemRowToFormInput(row)]));

  // Ids livres são criados já nesta request; os existentes com a mesma configuração são só
  // pulados, e os divergentes voltam como conflito pro client perguntar item a item se substitui
  // (via PATCH) — sem travar a criação dos demais.
  const created: number[] = [];
  const skipped: number[] = [];
  const conflicts: { existing: ItemInput; incoming: ItemInput }[] = [];
  for (const id of ids) {
    const incoming = incomingById.get(id)!;
    const existing = existingById.get(id);
    if (!existing) created.push(id);
    else if (isSameItemConfig(existing, incoming)) skipped.push(id);
    else conflicts.push({ existing, incoming });
  }

  if (created.length > 0) {
    await prisma.item.createMany({
      data: created.map((id) => itemFormToRow(incomingById.get(id)!)),
    });
    for (const id of created) {
      await syncAutoGeneratedEquipMovements(prisma, id, item.slotType);
    }
  }

  await logAudit({
    accountId: Number(session.user.id),
    action: "create",
    entity: "item",
    metadata: {
      name: item.name,
      fromId,
      toId,
      count: created.length,
      skipped: skipped.length,
      conflicts: conflicts.length,
    },
  });

  return NextResponse.json(
    { created, skipped, conflicts, fromId, toId },
    { status: created.length > 0 ? 201 : 200 },
  );
});
