import { NextResponse } from "next/server";
import type { Prisma } from "@/lib/generated/prisma/client";

import { requireAdminSession } from "@/lib/api-guard";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { buildPaginatedResult, parsePaginationParams } from "@/lib/pagination";
import { itemSchema } from "@/lib/validations/admin/item";
import { itemFormToRow, itemRowToFormInput } from "@/lib/item-mapper";
import { syncAutoGeneratedEquipMovements } from "@/lib/movement-mapper";

const ITEM_LIST_SELECT = {
  id: true,
  name: true,
  article: true,
  description: true,
  type: true,
  weaponType: true,
  slotType: true,
  weight: true,
  attack: true,
  defense: true,
  armor: true,
  worth: true,
  skills: true,
  published: true,
} as const;

export async function GET(request: Request) {
  const { response } = await requireAdminSession();
  if (response) return response;

  const url = new URL(request.url);
  const { page, pageSize, search } = parsePaginationParams(url);
  const type = url.searchParams.get("type");
  const weaponType = url.searchParams.get("weaponType");
  const slotType = url.searchParams.get("slotType");
  const published = url.searchParams.get("published");
  const idMin = url.searchParams.get("idMin");
  const idMax = url.searchParams.get("idMax");

  const where: Prisma.ItemWhereInput = {
    ...(search
      ? {
          OR: [
            { name: { contains: search } },
            ...(Number.isFinite(Number(search))
              ? [{ id: Number(search) }]
              : []),
          ],
        }
      : {}),
    ...(type ? { type } : {}),
    ...(weaponType ? { weaponType } : {}),
    ...(slotType ? { slotType } : {}),
    ...(published ? { published: published === "true" } : {}),
    ...(idMin || idMax
      ? {
          id: {
            ...(idMin ? { gte: Number(idMin) } : {}),
            ...(idMax ? { lte: Number(idMax) } : {}),
          },
        }
      : {}),
  };

  const [items, total] = await Promise.all([
    prisma.item.findMany({
      where,
      orderBy: { id: "asc" },
      select: ITEM_LIST_SELECT,
      skip: (page - 1) * pageSize,
      take: pageSize,
    }),
    prisma.item.count({ where }),
  ]);

  return NextResponse.json(buildPaginatedResult(items, total, page, pageSize));
}

export async function POST(request: Request) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const body = await request.json();
  const parsed = itemSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Dados inválidos." },
      { status: 422 },
    );
  }

  const existing = await prisma.item.findUnique({
    where: { id: parsed.data.id },
  });
  if (existing) {
    return NextResponse.json(
      { error: "Já existe um item com esse id." },
      { status: 409 },
    );
  }

  const item = await prisma.item.create({ data: itemFormToRow(parsed.data) });
  await syncAutoGeneratedEquipMovements(prisma, item.id, item.slotType);

  await logAudit({
    accountId: Number(session.user.id),
    action: "create",
    entity: "item",
    entityId: item.id,
    metadata: { name: item.name },
  });

  return NextResponse.json({ item: itemRowToFormInput(item) }, { status: 201 });
}
