import { NextResponse } from "next/server";

import { requireAdminSession } from "@/lib/api-guard";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { withAudit } from "@/lib/api-audit-wrapper";
import { syncAutoGeneratedEquipMovements } from "@/lib/movement-mapper";

const MAX_IDS = 2000;
const CHUNK_SIZE = 500;

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));
  return chunks;
}

export const POST = withAudit(async function POST(request: Request) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const body: unknown = await request.json().catch(() => null);
  const rawIds = body && typeof body === "object" && "ids" in body ? (body as { ids: unknown }).ids : null;
  const ids: number[] = Array.isArray(rawIds)
    ? rawIds.filter((value): value is number => Number.isInteger(value)).slice(0, MAX_IDS)
    : [];

  if (ids.length === 0) {
    return NextResponse.json({ error: "Nenhum id válido informado." }, { status: 422 });
  }

  // Movements auto-gerados de equip não têm FK pro item — limpa antes de apagar cada um, senão
  // ficam órfãos apontando pra um item que não existe mais.
  for (const id of ids) {
    await syncAutoGeneratedEquipMovements(prisma, id, "");
  }

  for (const idsChunk of chunk(ids, CHUNK_SIZE)) {
    await prisma.item.deleteMany({ where: { id: { in: idsChunk } } });
  }

  await logAudit({
    accountId: Number(session.user.id),
    action: "bulk_delete",
    entity: "item",
    metadata: { deletedCount: ids.length, deletedIds: ids },
  });

  return NextResponse.json({ deletedCount: ids.length });
});
