import { NextResponse } from "next/server";

import { requireAdminSession } from "@/lib/api-guard";
import { prisma } from "@/lib/prisma";
import { logAudit } from "@/lib/audit";
import { itemSchema } from "@/lib/validations/admin/item";
import { itemFormToRow, itemRowToFormInput } from "@/lib/item-mapper";
import { syncAutoGeneratedEquipMovements } from "@/lib/movement-mapper";

type Params = { params: Promise<{ id: string }> };

export async function GET(_request: Request, { params }: Params) {
  const { response } = await requireAdminSession();
  if (response) return response;

  const { id } = await params;
  const item = await prisma.item.findUnique({ where: { id: Number(id) } });

  if (!item) {
    return NextResponse.json({ error: "Item não encontrado." }, { status: 404 });
  }

  return NextResponse.json({ item: itemRowToFormInput(item) });
}

export async function PATCH(request: Request, { params }: Params) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const { id } = await params;
  const body = await request.json();
  const parsed = itemSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      { error: parsed.error.issues[0]?.message ?? "Dados inválidos." },
      { status: 422 }
    );
  }

  const duplicate = await prisma.item.findFirst({
    where: { id: parsed.data.id, NOT: { id: Number(id) } },
  });
  if (duplicate) {
    return NextResponse.json({ error: "Já existe um item com esse id." }, { status: 409 });
  }

  const data = itemFormToRow(parsed.data);
  const item = await prisma.item.update({
    where: { id: Number(id) },
    data: { ...data, id: parsed.data.id },
  });

  if (item.id !== Number(id)) {
    // Id do item mudou — os movements auto-gerados antigos ficariam órfãos (Movement.itemId
    // não é FK), então limpa os do id antigo antes de sincronizar para o novo.
    await syncAutoGeneratedEquipMovements(prisma, Number(id), "");
  }
  await syncAutoGeneratedEquipMovements(prisma, item.id, item.slotType);

  await logAudit({
    accountId: Number(session.user.id),
    action: "update",
    entity: "item",
    entityId: item.id,
    metadata: { name: item.name },
  });

  return NextResponse.json({ item: itemRowToFormInput(item) });
}

export async function DELETE(_request: Request, { params }: Params) {
  const { session, response } = await requireAdminSession();
  if (response) return response;

  const { id } = await params;
  await syncAutoGeneratedEquipMovements(prisma, Number(id), "");
  await prisma.item.delete({ where: { id: Number(id) } });

  await logAudit({
    accountId: Number(session.user.id),
    action: "delete",
    entity: "item",
    entityId: id,
  });

  return NextResponse.json({ success: true });
}
