"use client";

import Link from "next/link";
import useSWR from "swr";
import { ExternalLink, Plus } from "lucide-react";

import { fetcher } from "@/lib/fetcher";
import type { MovementInput } from "@/lib/validations/admin/movement";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

type LinkedMovement = { id: number; input: MovementInput };

function selectorSummary(input: MovementInput): string {
  if (input.selectorType === "ITEM_ID") {
    return input.itemIdRangeEnd != null && input.itemIdRangeEnd !== input.itemId
      ? `item ${input.itemId}-${input.itemIdRangeEnd}`
      : `item ${input.itemId}`;
  }
  if (input.selectorType === "ITEM_RANGE") {
    return input.ranges.map((r) => `${r.from}-${r.to}`).join(", ");
  }
  return input.selectorType;
}

/** Lista somente-leitura de `Movement` cujo seletor cobre este item (`GET
 * /api/admin/movements?itemId=X`) — não edita nada aqui, só mostra e linka para
 * `/admin/movements/[id]` ou para criar um novo já pré-preenchido com este item. */
export function ItemLinkedMovementsPanel({ itemId }: { itemId: number }) {
  const { data, isLoading } = useSWR<{ data: LinkedMovement[] }>(
    `/api/admin/movements?itemId=${itemId}`,
    fetcher
  );

  const movements = data?.data ?? [];

  return (
    <div className="flex flex-col gap-3">
      <p className="text-sm text-muted-foreground">
        Movements cujo seletor (item id, range, fromid/toid) cobre o item #{itemId}. Somente
        leitura — edite a partir da tela de Movements.
      </p>

      {isLoading && <p className="text-sm text-muted-foreground">Carregando...</p>}

      {!isLoading && movements.length === 0 && (
        <p className="text-sm text-muted-foreground">Nenhum movement vinculado a este item.</p>
      )}

      <div className="flex flex-col gap-2">
        {movements.map((movement) => (
          <div
            key={movement.id}
            className="flex items-center justify-between gap-2 rounded-md border p-2 text-sm"
          >
            <div className="flex flex-col">
              <span className="flex items-center gap-2 font-medium">
                {movement.input.eventType} — {selectorSummary(movement.input)}
                {movement.input.autoGenerated && (
                  <Badge variant="secondary" className="text-xs">
                    Automático
                  </Badge>
                )}
              </span>
              <span className="text-xs text-muted-foreground">
                {movement.input.actionKind === "SCRIPT" ? "script" : "function"}:{" "}
                {movement.input.actionValue}
                {movement.input.slot ? ` · slot: ${movement.input.slot}` : ""}
              </span>
            </div>
            <Button
              variant="ghost"
              size="icon-sm"
              nativeButton={false}
              render={<Link href={`/admin/movements/${movement.id}`} />}
            >
              <ExternalLink className="size-4" />
            </Button>
          </div>
        ))}
      </div>

      <Button
        type="button"
        variant="outline"
        size="sm"
        className="self-start"
        nativeButton={false}
        render={<Link href={`/admin/movements/new?itemId=${itemId}`} />}
      >
        <Plus className="size-4" />
        Criar movement para este item
      </Button>
    </div>
  );
}
