import { Prisma } from "@/lib/generated/prisma/client";
import type { Movement, PrismaClient } from "@/lib/generated/prisma/client";
import type { MovementInput } from "@/lib/validations/admin/movement";

export function movementFormToRow(
  input: MovementInput,
): Prisma.MovementUncheckedCreateInput {
  return {
    eventType: input.eventType,
    tileItem: input.tileItem,

    selectorType: input.selectorType,
    itemId: input.itemId,
    itemIdRangeEnd: input.itemIdRangeEnd,
    fromIds: input.ranges.length
      ? (input.ranges.map((r) => r.from) as Prisma.InputJsonValue)
      : Prisma.JsonNull,
    toIds: input.ranges.length
      ? (input.ranges.map((r) => r.to) as Prisma.InputJsonValue)
      : Prisma.JsonNull,
    uniqueId: input.uniqueId,
    actionId: input.actionId,

    slot: input.slot,
    level: input.level,
    magicLevel: input.magicLevel,
    premium: input.premium,

    actionKind: input.actionKind,
    actionValue: input.actionValue,
    luaScriptId: input.luaScriptId,
  };
}

type MovementRow = Movement & { vocations?: { vocationId: number }[] };

export function movementRowToFormInput(movement: MovementRow): MovementInput {
  const fromIds = (movement.fromIds as number[] | null) ?? [];
  const toIds = (movement.toIds as number[] | null) ?? [];
  const ranges = fromIds.map((from, index) => ({
    from,
    to: toIds[index] ?? from,
  }));

  return {
    eventType: movement.eventType as MovementInput["eventType"],
    tileItem: movement.tileItem,

    selectorType: movement.selectorType as MovementInput["selectorType"],
    itemId: movement.itemId,
    itemIdRangeEnd: movement.itemIdRangeEnd,
    ranges,
    uniqueId: movement.uniqueId,
    actionId: movement.actionId,

    slot: movement.slot,
    level: movement.level,
    magicLevel: movement.magicLevel,
    premium: movement.premium,

    actionKind: movement.actionKind as MovementInput["actionKind"],
    actionValue: movement.actionValue,
    luaScriptId: movement.luaScriptId,

    vocations: (movement.vocations ?? []).map((v) => ({
      vocationId: v.vocationId,
    })),

    autoGenerated: movement.autoGenerated,
  };
}

/** Um item id "pertence" a um movevent quando o seletor é ITEM_ID (id exato ou dentro do
 * range `id..itemIdRangeEnd`) ou ITEM_RANGE (dentro de algum par `from..to`). Usado pela
 * seção "Movements vinculados" do formulário de Item — não dá para expressar isso num
 * `WHERE` do Prisma (os pares ficam em JSON), então o filtro fino é feito em JS sobre um
 * conjunto de candidatos já reduzido pela query. */
export function movementMatchesItemId(
  movement: MovementInput,
  targetItemId: number,
): boolean {
  if (movement.selectorType === "ITEM_ID") {
    if (movement.itemId == null) return false;
    const rangeEnd = movement.itemIdRangeEnd ?? movement.itemId;
    return targetItemId >= movement.itemId && targetItemId <= rangeEnd;
  }

  if (movement.selectorType === "ITEM_RANGE") {
    return movement.ranges.some(
      (range) => targetItemId >= range.from && targetItemId <= range.to,
    );
  }

  return false;
}

/** `Item.slotType` usa um vocabulário um pouco diferente de `Movement.slot` (ver
 * MOVEMENT_SLOTS em validations/admin/movement.ts) — mapeia os poucos casos divergentes
 * (body→armor, two-handed→hands) e repassa o resto como está. */
const ITEM_SLOT_TO_MOVEMENT_SLOT: Record<string, string> = {
  body: "armor",
  "two-handed": "hands",
};

function movementSlotForItemSlot(itemSlotType: string): string {
  return ITEM_SLOT_TO_MOVEMENT_SLOT[itemSlotType] ?? itemSlotType;
}

/**
 * Cria/atualiza/remove os movements Equip+DeEquip auto-gerados a partir do `Item.slotType`
 * (ver item 4 do AGENTS.md). Só mexe em movements com `autoGenerated: true` — nunca toca em
 * movements que o admin tenha criado manualmente para o mesmo item/evento.
 */
export async function syncAutoGeneratedEquipMovements(
  prisma: PrismaClient,
  itemId: number,
  itemSlotType: string,
): Promise<void> {
  const existing = await prisma.movement.findMany({
    where: {
      itemId,
      selectorType: "ITEM_ID",
      autoGenerated: true,
      eventType: { in: ["Equip", "DeEquip"] },
    },
  });

  if (!itemSlotType) {
    if (existing.length) {
      await prisma.movement.deleteMany({
        where: { id: { in: existing.map((m) => m.id) } },
      });
    }
    return;
  }

  const slot = movementSlotForItemSlot(itemSlotType);
  const specs: { eventType: "Equip" | "DeEquip"; actionValue: string }[] = [
    { eventType: "Equip", actionValue: "onEquipItem" },
    { eventType: "DeEquip", actionValue: "onDeEquipItem" },
  ];

  for (const spec of specs) {
    const current = existing.find((m) => m.eventType === spec.eventType);

    if (current) {
      await prisma.movement.update({
        where: { id: current.id },
        data: { slot, actionKind: "FUNCTION", actionValue: spec.actionValue },
      });
    } else {
      await prisma.movement.create({
        data: {
          eventType: spec.eventType,
          selectorType: "ITEM_ID",
          itemId,
          slot,
          actionKind: "FUNCTION",
          actionValue: spec.actionValue,
          autoGenerated: true,
        },
      });
    }
  }
}
