import type { Prisma, Spell, SpellVocation } from "@/lib/generated/prisma/client";
import { defaultSpellValues, type SpellFormInput } from "@/lib/validations/admin/spell";

/** Só os campos escalares de `Spell` — as linhas de `spell_vocations` são gravadas à parte
 * (deleteMany + createMany numa transação), ver rotas de create/update. */
export function spellFormToScalarData(input: SpellFormInput): Prisma.SpellUncheckedCreateInput {
  return {
    kind: input.kind,
    name: input.name,
    words: input.words,
    runeItemId: input.runeItemId,
    level: input.level,
    magicLevel: input.magicLevel,
    mana: input.mana,
    manaPercent: input.manaPercent,
    soul: input.soul,
    exhaustion: input.exhaustion,
    enabled: input.enabled,
    premium: input.premium,
    needTarget: input.needTarget,
    needWeapon: input.needWeapon,
    selfTarget: input.selfTarget,
    needLearn: input.needLearn,
    range: input.range,
    blockType: input.blockType,
    aggressive: input.aggressive,
    blockWalls: input.blockWalls,
    allowFarUse: input.allowFarUse,
    hasParam: input.hasParam,
    needDirection: input.needDirection,
    casterTargetOrDirection: input.casterTargetOrDirection,
    limitRange: input.limitRange,
    hasCharges: input.hasCharges,
    conjureId: input.conjureId,
    conjureCount: input.conjureCount,
    conjureReagentId: input.conjureReagentId,
    event: input.event,
    scriptValue: input.scriptValue,
    functionName: input.functionName,
    description: input.description,
    group: input.group,
    published: input.published,
  };
}

export function spellToFormInput(spell: Spell & { vocations: SpellVocation[] }): SpellFormInput {
  return {
    ...defaultSpellValues,
    kind: spell.kind as SpellFormInput["kind"],
    name: spell.name,
    words: spell.words,
    runeItemId: spell.runeItemId,
    level: spell.level,
    magicLevel: spell.magicLevel,
    mana: spell.mana,
    manaPercent: spell.manaPercent,
    soul: spell.soul,
    exhaustion: spell.exhaustion,
    enabled: spell.enabled,
    premium: spell.premium,
    needTarget: spell.needTarget,
    needWeapon: spell.needWeapon,
    selfTarget: spell.selfTarget,
    needLearn: spell.needLearn,
    range: spell.range,
    blockType: spell.blockType as SpellFormInput["blockType"],
    aggressive: spell.aggressive,
    blockWalls: spell.blockWalls,
    allowFarUse: spell.allowFarUse,
    hasParam: spell.hasParam,
    needDirection: spell.needDirection,
    casterTargetOrDirection: spell.casterTargetOrDirection,
    limitRange: spell.limitRange,
    hasCharges: spell.hasCharges,
    conjureId: spell.conjureId,
    conjureCount: spell.conjureCount,
    conjureReagentId: spell.conjureReagentId,
    event: spell.event,
    scriptValue: spell.scriptValue,
    functionName: spell.functionName,
    description: spell.description,
    group: spell.group,
    published: spell.published,
    vocations: spell.vocations.map((vocation) => ({
      vocationId: vocation.vocationId,
      showInDescription: vocation.showInDescription,
    })),
  };
}
