import type { Vocation } from "@/lib/generated/prisma/client";
import type { VocationInput } from "@/lib/validations/admin/vocation";

export function vocationToInput(vocation: Vocation): VocationInput {
  return {
    id: vocation.id,
    name: vocation.name,
    description: vocation.description,
    needpremium: vocation.needpremium,
    published: vocation.published,
    gaincap: vocation.gaincap,
    gainhp: vocation.gainhp,
    gainmana: vocation.gainmana,
    gainhpticks: vocation.gainhpticks,
    gainhpamount: vocation.gainhpamount,
    gainmanaticks: vocation.gainmanaticks,
    gainmanaamount: vocation.gainmanaamount,
    manamultiplier: vocation.manamultiplier,
    attackspeed: vocation.attackspeed,
    soulmax: vocation.soulmax,
    gainsoulticks: vocation.gainsoulticks,
    fromvoc: vocation.fromvoc,
    typeClassId: vocation.typeClassId,
    typeUniverseId: vocation.typeUniverseId,
    formula: {
      meleeDamage: vocation.formulaMeleeDamage,
      distDamage: vocation.formulaDistDamage,
      wandDamage: vocation.formulaWandDamage,
      magDamage: vocation.formulaMagDamage,
      magHealingDamage: vocation.formulaMagHealingDamage,
      defense: vocation.formulaDefense,
      magDefense: vocation.formulaMagDefense,
      armor: vocation.formulaArmor,
    },
    skill: {
      fist: vocation.skillFist,
      club: vocation.skillClub,
      sword: vocation.skillSword,
      axe: vocation.skillAxe,
      distance: vocation.skillDistance,
      shielding: vocation.skillShielding,
      fishing: vocation.skillFishing,
      experience: vocation.skillExperience,
    },
  };
}

export function vocationInputToPrismaData(input: VocationInput) {
  return {
    id: input.id,
    name: input.name,
    description: input.description,
    needpremium: input.needpremium,
    published: input.published,
    gaincap: input.gaincap,
    gainhp: input.gainhp,
    gainmana: input.gainmana,
    gainhpticks: input.gainhpticks,
    gainhpamount: input.gainhpamount,
    gainmanaticks: input.gainmanaticks,
    gainmanaamount: input.gainmanaamount,
    manamultiplier: input.manamultiplier,
    attackspeed: input.attackspeed,
    soulmax: input.soulmax,
    gainsoulticks: input.gainsoulticks,
    fromvoc: input.fromvoc,
    typeClassId: input.typeClassId,
    typeUniverseId: input.typeUniverseId,
    formulaMeleeDamage: input.formula.meleeDamage,
    formulaDistDamage: input.formula.distDamage,
    formulaWandDamage: input.formula.wandDamage,
    formulaMagDamage: input.formula.magDamage,
    formulaMagHealingDamage: input.formula.magHealingDamage,
    formulaDefense: input.formula.defense,
    formulaMagDefense: input.formula.magDefense,
    formulaArmor: input.formula.armor,
    skillFist: input.skill.fist,
    skillClub: input.skill.club,
    skillSword: input.skill.sword,
    skillAxe: input.skill.axe,
    skillDistance: input.skill.distance,
    skillShielding: input.skill.shielding,
    skillFishing: input.skill.fishing,
    skillExperience: input.skill.experience,
  };
}
