import { z } from "zod";

export const MOVEMENT_EVENT_TYPES = [
  "StepIn",
  "StepOut",
  "Equip",
  "DeEquip",
  "AddItem",
  "RemoveItem",
] as const;
export type MovementEventType = (typeof MOVEMENT_EVENT_TYPES)[number];

export const MOVEMENT_SELECTOR_TYPES = [
  "ITEM_ID",
  "ITEM_RANGE",
  "UNIQUE_ID",
  "ACTION_ID",
] as const;
export type MovementSelectorType = (typeof MOVEMENT_SELECTOR_TYPES)[number];

/** Valores canônicos de `slot=` — só relevantes para Equip/DeEquip. */
export const MOVEMENT_SLOTS = [
  "",
  "head",
  "necklace",
  "backpack",
  "armor",
  "left-hand",
  "right-hand",
  "hands",
  "hand",
  "legs",
  "feet",
  "ring",
  "ammo",
  "pickupable",
  "wherever",
] as const;
export type MovementSlot = (typeof MOVEMENT_SLOTS)[number];

export const MOVEMENT_ACTION_KINDS = ["SCRIPT", "FUNCTION"] as const;
export type MovementActionKind = (typeof MOVEMENT_ACTION_KINDS)[number];

/** Únicos 4 nomes que `MoveEvent::loadFunction` reconhece no engine. */
export const MOVEMENT_FUNCTION_NAMES = [
  "onEquipItem",
  "onDeEquipItem",
  "onStepInField",
  "onAddField",
] as const;
export type MovementFunctionName = (typeof MOVEMENT_FUNCTION_NAMES)[number];

export const movementVocationSchema = z.object({
  vocationId: z.number().int(),
});
export type MovementVocationInput = z.infer<typeof movementVocationSchema>;

/** Um par `fromid`/`toid` — `ITEM_RANGE` pode ter vários pares em paralelo (listas
 * `;`-separadas no XML, ex.: `fromid="100;200" toid="105;205"`). Modelado como lista de
 * pares (não dois arrays paralelos) para caber num `useFieldArray` no form. */
export const movementIdRangeSchema = z.object({
  from: z.number().int(),
  to: z.number().int(),
});
export type MovementIdRangeInput = z.infer<typeof movementIdRangeSchema>;

export const movementSchema = z.object({
  eventType: z.enum(MOVEMENT_EVENT_TYPES),
  tileItem: z.boolean(),

  selectorType: z.enum(MOVEMENT_SELECTOR_TYPES),
  itemId: z.number().int().nullable(),
  itemIdRangeEnd: z.number().int().nullable(),
  ranges: z.array(movementIdRangeSchema),
  uniqueId: z.number().int().nullable(),
  actionId: z.number().int().nullable(),

  slot: z.string().max(20),
  level: z.number().int(),
  magicLevel: z.number().int(),
  premium: z.boolean(),

  actionKind: z.enum(MOVEMENT_ACTION_KINDS),
  actionValue: z.string().max(255),
  /** Vínculo opcional de conveniência com um LuaScript cadastrado — nunca obrigatório,
   * nem usado no XML exportado (só `actionValue`). */
  luaScriptId: z.number().int().nullable(),

  vocations: z.array(movementVocationSchema),

  /** Só leitura no form — marca movements criados automaticamente a partir do
   * `Item.slotType` (ver syncAutoGeneratedEquipMovements em lib/movement-mapper.ts). */
  autoGenerated: z.boolean(),
});

export type MovementInput = z.infer<typeof movementSchema>;

export const defaultMovementValues: MovementInput = {
  eventType: "StepIn",
  tileItem: false,

  selectorType: "ITEM_ID",
  itemId: null,
  itemIdRangeEnd: null,
  ranges: [],
  uniqueId: null,
  actionId: null,

  slot: "",
  level: 0,
  magicLevel: 0,
  premium: false,

  actionKind: "SCRIPT",
  actionValue: "",
  luaScriptId: null,

  vocations: [],

  autoGenerated: false,
};

export const emptyMovementIdRange: MovementIdRangeInput = { from: 0, to: 0 };
